### ISSUE TITLE
Not required

### ISSUE THREAD

**Issue by human-divanshu** [MANISH007700/Binary-Num#1]
https://github.com/MANISH007700/Binary-Num/blob/05a1785db5477eeec78d65f5d8a6f87c4a6bcdc4/Binary#L23

First of all, you should not be using builtin functions to convert to binary. No good company would accept this solution. Either you convert them to binary by your own code or use bitwise without any need to convert to binary.
Also, question caption mentioned "bitwise interview question"
Watch these videos for more info about bitwise operators
[https://www.youtube.com/playlist?list=PLGMFAdS4pdNCQDz-BwM7x8L15wg77A01X](https://www.youtube.com/playlist?list=PLGMFAdS4pdNCQDz-BwM7x8L15wg77A01X)

**Comment by MANISH007700** [comment]
Sure , will keep in mind !
